version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: flyway_postgres
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  flyway:
    image: flyway/flyway:latest
    container_name: flyway_migration
    command: -configFiles=/flyway/conf/flyway.conf migrate
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway/conf:/flyway/conf
    depends_on:
      - postgres
